import bhadepayimg from "./bhadepay.png"
import botwot from "./botwot.png"
import myaimate from "./myaimate.png"
import fretbox from "./fretbox.png"
import superdm from "./superdm.png"
import ait from "./ait.png"
import aps from "./aps.png"
import mindtickle from "./mindtickle.png"   
import dobr from "./dobr.png"
import Profile1 from "./Profile1.jpeg"
export {bhadepayimg, botwot, myaimate, fretbox, superdm, ait, aps, mindtickle, dobr, Profile1 as Profile}
